Create authorization flow
IgorOsiyuk/iTechArt-Laba_back pull request #1
Opened 2021-04-14 14:23 UTC by IgorOsiyuk

main URL: https://i-tech-art-laba-back.vercel.app/

POST /api/user/signup   - registration
POST /api/user/signin  -  login
GET /api/keeps  -- request for all user's keeps
POST /api/keeps  -- request for add new user keep
DELETE  /api/keeps  -- delete user's keep by id keep

2021-04-15 13:03 UTC, melonholy requested changes

2021-04-15 13:03 UTC, melonholy commented
Also add unique HTTP codes for response

2021-04-16 06:17 UTC, IgorOsiyuk commented on config/db.ts
> +const BD_URL: string = process.env.DB_CONNECT || "";
Add check сondition and now I'm checking if BD_URL exist that do next codes

2021-04-16 06:18 UTC, IgorOsiyuk commented on controllers/index.ts
> +        res.header('Authorization', response).json()
now I send token in body  
![image](https://user-images.githubusercontent.com/68943103/114980113-a6758480-9e94-11eb-92a3-140f1b4a1bc4.png)

2021-04-16 06:19 UTC, IgorOsiyuk commented on index.ts
> +import keepsRoute from './routes/keeps';
+

2021-04-16 06:24 UTC, IgorOsiyuk commented on models/Keep.ts
> +        type: String,
+

2021-04-16 06:27 UTC, IgorOsiyuk commented on routes/auth.ts
> +const controllers = require('../controllers');
- [+]

2021-04-16 06:30 UTC, IgorOsiyuk commented on services/keepService.ts
> +    const keep = await KeepModel.findById(idKeep).findOneAndRemove()
- [+]

2021-04-16 06:31 UTC, IgorOsiyuk commented on services/serviceTypes.ts
> +    age: string;
- [+]

2021-04-16 06:34 UTC, IgorOsiyuk commented on services/userService.ts
> +    const user = await UserModel.findOne({ email: email })
- [+]

2021-04-16 06:35 UTC, IgorOsiyuk commented on services/userService.ts
> +    const existUser = await UserModel.findOne({ email: email });
- [+]

2021-04-16 06:36 UTC, IgorOsiyuk commented on services/userService.ts
> +            const tokenSecret:string = process.env.TOKEN_SECRET || "";
- [+]

2021-04-16 08:04 UTC, IgorOsiyuk commented on services/userService.ts
> +            const token = await jwt.sign({ _id: existUser._id }, tokenSecret);
- [+]
 token time is expiring after 24

2021-04-16 08:50 UTC, IgorOsiyuk commented on services/keepService.ts
> +const getKeep = async (userID: Express.User | undefined) => {
changed types for Express.User and replace this validation from services to controllers

2021-04-16 08:50 UTC, IgorOsiyuk commented on services/keepService.ts
> +const postKeep = async (data: serviceTypes.Keep, userID: Express.User | undefined) => {
changed types for Express.User and replace this validation from services to controllers

2021-04-19 10:30 UTC, melonholy requested changes

2021-04-19 10:30 UTC, melonholy commented on @types/express/index.d.ts
> +}
missed new line

2021-04-19 10:30 UTC, melonholy commented on controllers/index.ts
> +        res.json({ token: response })
You can name it `token` and make `res.json({ token })`

2021-04-19 10:30 UTC, melonholy commented on controllers/index.ts
> +    if (req.user?._id) {
Unnecessary check, your passport middleware shouldn't pass you in this controller if user hasn't passed check

2021-04-19 10:30 UTC, melonholy commented on controllers/index.ts
> +    if (req.user?._id) {
See comment above

2021-04-19 10:30 UTC, melonholy commented on controllers/index.ts
> +            const allUserKeeps = await keepService.getKeep(req.user._id);
Name it keeps

2021-04-19 10:30 UTC, melonholy commented on services/keepService.ts
> +    }
You can change flow to 
```
if(!keeps)
    const error = [{
        msg: 'Something goes wrong Our droids fix it tomorrow'
    }]
    throw error

  return keeps

```

2021-04-19 10:30 UTC, melonholy commented on services/serviceTypes.ts
> +export interface RegData {
You can extend LoginDate interface, so it will be export

```
interface RegData extends LoginData {
    name: string;
    age?: number;
    date: Date;
}
```

2021-04-19 10:30 UTC, melonholy commented on services/userService.ts
> +                    expiresIn:"24h"
You should put number in ms and move it in env file

2021-04-19 13:39 UTC, IgorOsiyuk commented on @types/express/index.d.ts
> +}
- [+]

2021-04-19 13:40 UTC, IgorOsiyuk commented on controllers/index.ts
> +        res.json({ token: response })
- [+]

2021-04-19 13:44 UTC, IgorOsiyuk commented on controllers/index.ts
> +    if (req.user?._id) {
this checking helps me avoid error from types undefined.
![image](https://user-images.githubusercontent.com/68943103/115246380-8103a780-a12e-11eb-8938-b79698268052.png)

2021-04-19 13:45 UTC, IgorOsiyuk commented on controllers/index.ts
> +            const allUserKeeps = await keepService.getKeep(req.user._id);
- [+]

2021-04-19 13:48 UTC, IgorOsiyuk commented on services/keepService.ts
> +    }
- [+]

2021-04-19 13:50 UTC, IgorOsiyuk commented on services/serviceTypes.ts
> +export interface RegData {
- [+]

2021-04-20 06:02 UTC, IgorOsiyuk commented on services/userService.ts
> +                    expiresIn:"24h"
- [+]

2021-04-20 07:57 UTC, IgorOsiyuk commented on controllers/index.ts
> +    if (req.user?._id) {
I changed my types and now User interface has the same type as UserShema 
![image](https://user-images.githubusercontent.com/68943103/115358580-7a287380-a1c6-11eb-864d-fdd82884edc2.png)
in my controller, I put "!" in my parameters that describe that I sure that object user exists 
![image](https://user-images.githubusercontent.com/68943103/115359114-06d33180-a1c7-11eb-9875-8e07b4407d22.png) 
Because controller starts his work only after passport return user object

2021-04-21 14:25 UTC, IgorOsiyuk commented on controllers/index.ts
> +    if (req.user?._id) {
- [+]

2021-04-23 10:27 UTC, melonholy approved these changes

2021-04-23 10:27 UTC, melonholy commented on services/userService.ts
> +                    expiresIn: process.env.TOKEN_LIFE_CICLE
CICLE?))))

2021-04-23 11:46 UTC, IgorOsiyuk commented on services/userService.ts
> +                    expiresIn: process.env.TOKEN_LIFE_CICLE
change to TIME

2021-04-23 11:47 UTC, merged